version: "3.7"

services:
  mini_project2:
    build:
      context: .
    image: mini_project2:$VERSION
    container_name: mini_project2
    ports:
      - "3810:6440"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped

